### ISSUE TITLE
support deep links

### ISSUE THREAD

**Issue by regular** [brainpm/bpm-webplayer#2]
use url fragments to display deep links in the address bar
Change the fragment when scrolling

**Comment by jfr3000** [comment]
stuff from your comment is done (https://github.com/regular/bpm-webplayer/commit/031a8a12fc52c2250834791b4a6160ff616d1400), but actual deep links don't work yet if that episode hasn't been unlocked by the user yet. any pointers?

**Comment by regular** [comment]
on page load, extract fragment from url, make sure the episode is loaded and scroll to it.

**Comment by regular** [comment]
After your change, the scrolling was bumpy. Reason: when you change location.hash, the browser searches for an anchor tag (`<a href="#something">`) and scrolls there. At lease for 'remote-thought'control' such an anchor did exist. (github-flavored markdown generates anchor tags for each h1)

I changed this behaviour in `bpm bundle`, the anchors are now prefixed with the episode's name. This partially fixed the jumping behaviour. The remaining issues is a noticeable delay  when the hash is changes, so the scrolling still isn't smooth (in latest Chrome)

We should try if this fixes the delay: http://stackoverflow.com/questions/3870057/how-can-i-update-window-location-hash-without-jumping-the-document

**Comment by jfr3000** [comment]
won't fix
