### ISSUE TITLE
add video credits

### ISSUE THREAD

**Issue by regular** [brainpm/bpm-webplayer#25]
brainpm-youtube should use the youtube API to try to find out information about a video's author and its license. This information should be displayed below the embedded video.
(this happens at `bpm bundle` time, not at runtime)

**Comment by jfr3000** [comment]
can you specify this one?

**Comment by regular** [comment]
closed via regular/brainpm-youtube@4ef5e6b01ab289916c55e74956b3f1607253bd2b
